In [37]:
import pandas as pd
import numpy as np

matches=pd.read_csv("C:\\Users\\gaurav\\Documents\\nagarro\\ipl_data\\matches.csv")
deliveries=pd.read_csv("C:\\Users\\gaurav\\Documents\\nagarro\\ipl_data\\deliveries.csv")

In [38]:
deliveries.info()
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 21 columns):
match_id            179078 non-null int64
inning              179078 non-null int64
batting_team        179078 non-null object
bowling_team        179078 non-null object
over                179078 non-null int64
ball                179078 non-null int64
batsman             179078 non-null object
non_striker         179078 non-null object
bowler              179078 non-null object
is_super_over       179078 non-null int64
wide_runs           179078 non-null int64
bye_runs            179078 non-null int64
legbye_runs         179078 non-null int64
noball_runs         179078 non-null int64
penalty_runs        179078 non-null int64
batsman_runs        179078 non-null int64
extra_runs          179078 non-null int64
total_runs          179078 non-null int64
player_dismissed    8834 non-null object
dismissal_kind      8834 non-null object
fielder             6448 non-null object
dtypes: int64(13), object(8)
memory usage: 28.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
id                 756 non-null int64
season             756 non-null int64
city               749 non-null object
date               756 non-null object
team1              756 non-null object
team2              756 non-null object
toss_winner        756 non-null object
toss_decision      756 non-null object
result             756 non-null object
dl_applied         756 non-null int64
winner             752 non-null object
win_by_runs        756 non-null int64
win_by_wickets     756 non-null int64
player_of_match    752 non-null object
venue              756 non-null object
umpire1            754 non-null object
umpire2            754 non-null object
umpire3            119 non-null object
dtypes: int64(5), object(13)
memory usage: 106.4+ KB

Which team has won/lost maximum number of matches while chasing?

In [41]:
played_last=[]
losers=[]
for i in range(len(matches)):
    to_be_appended=matches.iloc[i]["team2"] if matches.iloc[i]["winner"]==matches.iloc[i]["team1"] else matches.iloc[i]["team1"]
    losers.append(to_be_appended)

    if(matches.iloc[i]["toss_decision"]=="field"):
        played_last.append(matches.iloc[i]["toss_winner"])
    else:
        to_be_appended=matches.iloc[i]["team2"] if matches.iloc[i]["team1"]==matches.iloc[i]["toss_winner"] else matches.iloc[i]["team1"]
        played_last.append(to_be_appended)
        
matches["chasing"]=played_last
matches["losers"]=losers

In [42]:
winner_df=matches[matches["winner"]==matches["chasing"]]
print(winner_df["winner"].value_counts().idxmax(),winner_df["winner"].value_counts().max())
losers_df=matches[matches["losers"]==matches["chasing"]]
print(losers_df["losers"].value_counts().idxmax(),losers_df["losers"].value_counts().max())

Kolkata Knight Riders 58
Delhi Daredevils 47

Which toss decision is best for each ground?

In [95]:

winners=matches[matches["toss_winner"]==matches["winner"]].groupby(["venue","toss_decision"]).count()['id']
dec_df=winners.unstack()
dec_df.fillna(0,inplace=True)
dec=[]
for i in range(len(dec_df)):
    if dec_df.iloc[i]["bat"]>dec_df.iloc[i]["field"]:
        dec.append("bat")
    else:
        dec.append("field")
dec_df["decision"]=dec
dec_df

#winners.agg(["winner",]).count()

toss_decision                                        bat  field decision
venue
ACA-VDCA Stadium                                     0.0    2.0    field
Barabati Stadium                                     2.0    3.0    field
Brabourne Stadium                                    4.0    3.0      bat
Buffalo Park                                         2.0    0.0      bat
De Beers Diamond Oval                                1.0    1.0    field
Dr DY Patil Sports Academy                           3.0    6.0    field
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Sta...   2.0    2.0    field
Dubai International Cricket Stadium                  1.0    2.0    field
Eden Gardens                                        12.0   31.0    field
Feroz Shah Kotla                                    13.0   20.0    field
Feroz Shah Kotla Ground                              2.0    3.0    field
Green Park                                           0.0    4.0    field
Himachal Pradesh Cricket Association Stadium         1.0    4.0    field
Holkar Cricket Stadium                               0.0    7.0    field
IS Bindra Stadium                                    0.0    5.0    field
JSCA International Stadium Complex                   1.0    3.0    field
Kingsmead                                            6.0    3.0      bat
M Chinnaswamy Stadium                                4.0   36.0    field
M. A. Chidambaram Stadium                            1.0    3.0    field
M. Chinnaswamy Stadium                               0.0    3.0    field
MA Chidambaram Stadium, Chepauk                     21.0    5.0      bat
Maharashtra Cricket Association Stadium              1.0   13.0    field
Nehru Stadium                                        1.0    1.0    field
New Wanderers Stadium                                0.0    3.0    field
Newlands                                             3.0    1.0      bat
OUTsurance Oval                                      1.0    1.0    field
Punjab Cricket Association IS Bindra Stadium, M...   1.0    5.0    field
Punjab Cricket Association Stadium, Mohali           5.0   11.0    field
Rajiv Gandhi International Stadium, Uppal            5.0   14.0    field
Rajiv Gandhi Intl. Cricket Stadium                   1.0    1.0    field
Sardar Patel Stadium, Motera                         3.0    3.0    field
Saurashtra Cricket Association Stadium               0.0    4.0    field
Sawai Mansingh Stadium                               6.0   19.0    field
Shaheed Veer Narayan Singh International Stadium     1.0    2.0    field
Sharjah Cricket Stadium                              0.0    2.0    field
Sheikh Zayed Stadium                                 3.0    2.0      bat
St George's Park                                     3.0    0.0      bat
Subrata Roy Sahara Stadium                           9.0    0.0      bat
SuperSport Park                                      3.0    5.0    field
Vidarbha Cricket Association Stadium, Jamtha         1.0    0.0      bat
Wankhede Stadium                                    11.0   26.0    field

In [98]:
matches.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,chasing,losers
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,Royal Challengers Bangalore,Royal Challengers Bangalore
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,Rising Pune Supergiant,Mumbai Indians
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,Kolkata Knight Riders,Gujarat Lions
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,Kings XI Punjab,Rising Pune Supergiant
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,Delhi Daredevils,Delhi Daredevils

In [109]:
print(matches['player_of_match'].value_counts().idxmax(),matches['player_of_match'].value_counts().max())
deliveries.head()

CH Gayle 21

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

- Which batsman has played maximum number of dot balls?

In [124]:
deliveries["player_dismissed"].fillna("0",inplace=True)
deliveries[(deliveries["player_dismissed"]=='0') & (deliveries["total_runs"]==0)]["batsman"].value_counts().idxmax()

'V Kohli'

Which batsmen came to crease but never got a chance to face a ball?

In [128]:
a=set(deliveries.batsman.unique())
b=set(deliveries.non_striker.unique())
b-a

{'A Nel', 'BW Hilfenhaus', 'C Ganapathy', 'TP Sudhindra'}

 Which bowler has hit for maximum number of 1s/2s/3s/4s/6s?

In [218]:
runs=deliveries.groupby(["total_runs","bowler"])
a=runs.count()["match_id"]
runs_df=a.unstack()
# print(runs_df.iloc[0].max(),runs_df.iloc[0].max())
runs_df=runs_df.transpose()
runs_df["bowler"]=runs_df.index

In [247]:
runs_df
for i in range(1,7):
    print("max ",i," runs",runs_df[runs_df[i] == runs_df[i].max()])
# a=runs_df[runs_df[1] == runs_df[1].max()]
# a["bowler"]

max  1  runs total_runs            0       1      2     3      4    5      6   7   8  10  \
bowler
Harbhajan Singh  1244.0  1549.0  203.0  14.0  295.0  3.0  143.0 NaN NaN NaN

total_runs                bowler
bowler
Harbhajan Singh  Harbhajan Singh
max  2  runs total_runs      0       1      2    3      4    5      6    7    8  10  \
bowler
DJ Bravo    825.0  1189.0  258.0  7.0  294.0  2.0  133.0  1.0  2.0 NaN

total_runs    bowler
bowler
DJ Bravo    DJ Bravo
max  3  runs total_runs       0      1      2     3      4    5      6   7   8  10   bowler
bowler
P Kumar     1075.0  923.0  167.0  18.0  343.0  7.0  104.0 NaN NaN NaN  P Kumar
max  4  runs total_runs      0      1      2     3      4    5      6    7    8  10  \
bowler
UT Yadav    942.0  959.0  180.0  15.0  389.0  4.0  113.0  2.0  1.0 NaN

total_runs    bowler
bowler
UT Yadav    UT Yadav
max  5  runs total_runs      0      1      2    3      4    5     6    7   8  10    bowler
bowler
AB Dinda    627.0  554.0  102.0  6.0  233.0  9.0  56.0  2.0 NaN NaN  AB Dinda
max  6  runs total_runs       0       1      2    3      4    5      6   7    8  10  \
bowler
PP Chawla   1100.0  1311.0  245.0  9.0  312.0  7.0  171.0 NaN  2.0 NaN

total_runs     bowler
bowler
PP Chawla   PP Chawla

- Which batsman got stumped out maximum number of times

In [269]:
a=deliveries[(deliveries["player_dismissed"]==deliveries["batsman"]) & (deliveries["dismissal_kind"]=="stumped")].groupby("batsman")
a=a.count()["match_id"]
a=pd.DataFrame(a)

In [271]:
a[a["match_id"]==a["match_id"].max()]

          match_id
batsman
SK Raina         8

Object `times` not found.

 Which non-striker has been part of maximum number of runouts?

In [293]:
a=deliveries[(deliveries["dismissal_kind"]=="run out")].groupby("non_striker")
a=a.count()["match_id"]
a=pd.DataFrame(a)

 Which non-striker has been part of maximum number of runouts?

In [290]:
a[a["match_id"]==a["match_id"].max()]

             match_id
non_striker
KD Karthik         16
SK Raina           16

team that won most toss

In [296]:
matches["toss_winner"].value_counts().idxmax()

'Mumbai Indians'

team that lost most toss

In [298]:
matches["toss_winner"].value_counts().idxmin()

'Rising Pune Supergiant'

man of the match overall

In [299]:
print(matches['player_of_match'].value_counts().idxmax(),matches['player_of_match'].value_counts().max())

CH Gayle 21

strongest team

In [302]:
matches["winner"].value_counts().idxmax()

'Mumbai Indians'

weekest team

In [303]:
matches["winner"].value_counts().idxmin()

'Rising Pune Supergiants'